spring:
  profiles:
    active: dev
    include: freemarker,mysql,redis,interceptor
  mvc:
    favicon:
      enabled: false

debug: true

server:
  servlet-path: /common # 默认servlet至接受静态资源

app:
  name: yjyboot
  description: description about ${app.name} application