spring:
  profiles:
    active: dev
  resources:
    static-locations: /resources/**
  mvc:
    static-path-pattern: /resources/**

debug: false

app:
  name: yjyboot
  description: description about ${app.name} application